;   PlatformIO Project Configuration File
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;Reference for ESP-NOW
;https://github.com/espressif/esp-idf/blob/47faecc3/components/esp_wifi/include/esp_now.h


[env:esp32dev]   #common settings shared by all environments below for specific board targe
#platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21/platform-espressif32.zip  # Tells PlatformIO which ESP32 platform package/version to use for the build.
platform = espressif32
framework = espidf           # which programming framework to use
monitor_speed = 115200       # Serial monitor baud rate
monitor_filters = direct     # show more raw monitor serial ouput  
board = esp32dev             # board type
